name: Lwjgl3 Build
on:
  workflow_dispatch:
  schedule:
  - cron: "20 5 1 * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build JRE JAR files
        run: |
          gradle :jre_lwjgl3glfw:build --no-daemon
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: lwjgl
          path: lwjgl3/*
